insert into public.products (
  id,
  slug,
  name,
  short_name,
  category,
  description,
  long_description,
  serving_note,
  image_url,
  price,
  accent_gradient,
  calories_label,
  prep_time_label,
  freshness_label,
  is_featured,
  is_available,
  sort_order
)
values
  (
    1,
    'baso-ikan-original',
    'Baso Ikan Original',
    'Original',
    'Signature',
    'Baso ikan goreng renyah dengan saus khas gurih-manis yang jadi favorit utama e-baso-ikan.',
    'Baso ikan signature dengan kulit luar renyah, bagian tengah tetap juicy, dan rasa ikan yang berani. Cocok untuk teman istirahat, pulang sekolah, atau sekadar pengin camilan hangat yang cepat datang.',
    'Pas untuk snack cepat dan gurih.',
    'https://images.unsplash.com/photo-1537081538824-2fcad5cb096b?auto=format&fit=crop&w=1200&q=80',
    15000,
    'from-[#1f5c57] via-[#2d7a72] to-[#8abfa7]',
    '240 kkal',
    '5-7 menit',
    'Digoreng Saat Dipesan',
    true,
    true,
    1
  ),
  (
    9,
    'baso-ikan-jumbo',
    'Baso Ikan Jumbo',
    'Jumbo',
    'Best Seller',
    'Porsi lebih besar, lebih puas, dan tetap renyah. Cocok untuk yang mau baso ikan dengan bite lebih tebal.',
    'Baso ikan jumbo dibuat untuk pelanggan yang suka tekstur lebih padat dan rasa gurih yang lebih lama terasa. Porsinya lebih besar, tampil lebih berani, dan pas untuk menu unggulan harian.',
    'Pilihan paling puas buat makan lebih kenyang.',
    'https://images.unsplash.com/photo-1537081538824-2fcad5cb096b?auto=format&fit=crop&w=1200&q=80',
    22000,
    'from-[#c96c43] via-[#de8657] to-[#f2c28f]',
    '320 kkal',
    '7-9 menit',
    'Baru Diangkat',
    true,
    true,
    2
  ),
  (
    10,
    'baso-ikan-mie',
    'Baso Ikan Mie',
    'Mie Hangat',
    'Comfort Bowl',
    'Perpaduan baso ikan dan mie hangat yang lebih mengenyangkan tanpa kehilangan rasa gurih lautnya.',
    'Baso ikan mie menghadirkan kombinasi kuah ringan, mie lembut, dan baso ikan gurih yang bikin menu ini terasa lebih lengkap. Cocok untuk jam makan siang atau ketika ingin menu yang lebih comforting.',
    'Paling pas untuk porsi makan siang.',
    'https://images.unsplash.com/photo-1651585594107-859f80b4ca3a?auto=format&fit=crop&w=1200&q=80',
    20000,
    'from-[#2d3b73] via-[#3b4e92] to-[#8aa1e6]',
    '390 kkal',
    '8-10 menit',
    'Diracik Saat Dipesan',
    false,
    true,
    3
  ),
  (
    11,
    'es-teh-manis',
    'Es Teh Manis',
    'Es Teh',
    'Minuman',
    'Minuman pendamping dingin yang ringan, segar, dan pas menyeimbangkan gurihnya baso ikan.',
    'Es teh manis diracik sederhana, dingin, dan bersih rasanya. Cocok jadi pasangan semua menu baso ikan, terutama untuk menjaga ritme rasa tetap segar dari gigitan pertama sampai terakhir.',
    'Paling cocok jadi partner semua menu gurih.',
    'https://images.unsplash.com/photo-1646121342684-fcba59cf845c?auto=format&fit=crop&w=1200&q=80',
    8000,
    'from-[#7a4c2c] via-[#a86d42] to-[#e7c59a]',
    '110 kkal',
    '2-3 menit',
    'Disajikan Dingin',
    false,
    true,
    4
  )
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  short_name = excluded.short_name,
  category = excluded.category,
  description = excluded.description,
  long_description = excluded.long_description,
  serving_note = excluded.serving_note,
  image_url = excluded.image_url,
  price = excluded.price,
  accent_gradient = excluded.accent_gradient,
  calories_label = excluded.calories_label,
  prep_time_label = excluded.prep_time_label,
  freshness_label = excluded.freshness_label,
  is_featured = excluded.is_featured,
  is_available = excluded.is_available,
  sort_order = excluded.sort_order,
  updated_at = timezone('utc', now());

delete from public.product_addons
where product_id in (1, 9, 10, 11);

insert into public.product_addons (
  product_id,
  code,
  label,
  price,
  is_active,
  sort_order
)
values
  (1, 'spicySauce', 'Ekstra Saus Pedas', 3000, true, 1),
  (1, 'extraCup', 'Kemasan Takeaway', 2000, true, 2),
  (9, 'spicySauce', 'Ekstra Saus Pedas', 3000, true, 1),
  (9, 'extraPortion', 'Tambah 1 Baso Jumbo', 7000, true, 2),
  (10, 'extraNoodle', 'Ekstra Mie', 4000, true, 1),
  (10, 'spicySauce', 'Ekstra Saus Pedas', 3000, true, 2),
  (11, 'lessSugar', 'Less Sugar', 0, true, 1),
  (11, 'lemonSlice', 'Tambah Lemon', 2000, true, 2);
